<div class="top_cart">
<?php $_cartQty = $this->getSummaryCount() ?>    
<?php $_items = $this->getRecentItems() ?>
<?php if(count($_items)): ?>
				<?php if ($_cartQty==1): ?>
								<p class="amount"><span>Carrello: </span><?php echo $this->__('<a href="%s" class="icon_cart">1 prodotto</a>', $this->getUrl('checkout/cart')) ?></p>
				<?php else: ?>
								<p class="amount"><span>Carrello: </span><?php echo $this->__('<a href="%s" class="icon_cart">%s prodotti</a>', $this->getUrl('checkout/cart'), $_cartQty) ?></p>
				<?php endif ?>
<?php else: ?>
				<p class="amount"><span>Carrello: </span><?php echo $this->__('0 prodotti') ?></p>
<?php endif ?>
</div>