<?php
/*
 include_once 'app/Mage.php';
Mage::app();
Mage::getSingleton('core/session', array('name' => 'frontend'));
*/

if(!function_exists("timeDiff")) {function timeDiff($firstTime,$lastTime)
{

    // convert to unix timestamps
    $firstTime=strtotime($firstTime);
    $lastTime=strtotime($lastTime);
    
    // perform subtraction to get the difference (in seconds) between times
    $timeDiff=$lastTime-$firstTime;
    
    // return the difference
    return $timeDiff;}}

$_productCollection = Mage::getResourceModel('catalogsearch/advanced_collection')
            ->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes())
            ->addMinimalPrice()
            ->addStoreFilter();

Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($_productCollection);
Mage::getSingleton('catalog/product_visibility')->addVisibleInSearchFilterToCollection($_productCollection);
                           
$productID;
                            
$todayDate = date('m/d/y');
$tomorrow = mktime(0, 0, 0, date('m'), date('d')+1, date('y'));
$tomorrowDate = date('m/d/y', $tomorrow);

$productOutput;     
     
$_productCollection->addAttributeToFilter('special_from_date', array('date' => true, 'to' => $todayDate))
    ->addAttributeToFilter('special_to_date', array('or'=> array(
    0 => array('date' => true, 'from' => $tomorrowDate),
    1 => array('is' => new Zend_Db_Expr('null')))
    ), 'left')
    ->setOrder('special_to_date', 'asc')
    ->getSelect()->limit( 1 );

$c = 0;
foreach($_productCollection as $_product){
    if($_product->getData('special_price')!=null){
        $productOutput .=  '<a href="'.$_product->getProductUrl().'">
        <img src="'.$this->helper('catalog/image')->init($_product, 'thumbnail')->resize(180).'" alt="'.$_product->getName().'" />
        </a><br />';
        
        $productOutput .= '<br/>'.$_product->getName().'<br /><br />';
        
    $specialPrice = $_product->getData('special_price');
    $orignalPrice = $_product->getData('price');
        $productOutput .= "<span class='old-price'>&euro; ". number_format($orignalPrice, 0) ."</span><br/>";
        $productOutput .= "<span class='special-price'>&euro; ".number_format($specialPrice, 0) ."</span><br/>";
        
       $productID=$_product->getId();                 

    }
    $c++;
}

if ($c > 0){
    $now = date("Ymd H:m:s");
    $difference = timeDiff($now, $_product->getSpecialToDate());
    $years = abs(floor($difference / 31536000));
    $days = abs(floor(($difference-($years * 31536000))/86400));
    $hours = abs(floor(($difference-($years * 31536000)-($days * 86400))/3600));
    $mins = abs(floor(($difference-($years * 31536000)-($days * 86400)-($hours * 3600))/60));#floor($difference / 60);
    
    # DG intestazione
    $toOutput = "<div id='hightlight-scadenza'><i>Offerta valida per:</i><br/><b>";
    
    if ($years > 0) {
        if ($years == 1)
            $toOutput .= $years . " Anno ";
        else
            $toOutput .= $years . " Anni ";
    }
    
    if ($days > 0) {
        if ($days == 1)
            $toOutput .= $days . " Giorno ";
        else
            $toOutput .= $days . " Giorni ";
    }
    
    if ($hours > 0) {
        if ($hours == 1)
            $toOutput .= $hours . " Ora ";
        else
            $toOutput .= $hours . " Ore ";
    } else {
        if ($mins == 1)
            $toOutput .= $mins . " Minuto ";
        else
            $toOutput .= $mins . " Minuti ";
    }
    
    # DG - echo finale
    $toOutput .= "</b></div>";
    
	if ($c > 0)
	{
		### Echo del box complessivo
		echo '<div class="block block-highlight"><div class="block-title"><strong>Vendita Lampo</strong></div><div class="block-content">';
		
		echo $toOutput;
		
		echo $productOutput;
		
		echo "</br><button type=\"button\" title=\"".$this->__('Add to Cart')."\" class=\"button\" onclick=\"setLocation('".Mage::getUrl('checkout/cart/add', array('product'=>$productID,'qty'=>1))."')\"><span><span>".$this->__('Add to Cart')."</span></span></button></div></div>";
	}
    
}

?>
