<?php
$data = Mage::getModel('privacy/privacy')->getPrivacyCondition();
if ($data->getId() == "")
	return;
?>
<div class="input-box privacy">
	<div class="agree">
		<p><?php echo $this->htmlEscape($data->getCheckboxText()) ?>&nbsp;<a href="<?php echo $this->getUrl('privacy/page');?>" title="" target="_blank">(<?php echo Mage::helper('privacy')->__("leggi l'informativa");?>)</a></p>

		<label for="agreement-<?php echo $data->getId()?>-yes">
			<span class="privacy-yes"><?=$this->__('Yes');?></span>
			<input type="radio" id="agreement-<?php echo $data->getId()?>-yes" name="agreement[<?php echo $data->getId()?>]" value="1" title="<?php echo $this->htmlEscape($data->getCheckboxText()) ?>" class="checkbox required-entry" />
		</label>

		<label for="agreement-<?php echo $data->getId()?>-no">
			<span class="privacy-no"><?=$this->__('No');?></span>
			<input type="radio" id="agreement-<?php echo $data->getId()?>-no" name="agreement[<?php echo $data->getId()?>]" value="0" title="<?php echo $this->htmlEscape($data->getCheckboxText()) ?>" class="checkbox" />
		</label>
	</div>
</div>